### ISSUE TITLE
Really good work

### ISSUE THREAD

**Issue by josh9060** [mdanics/fluttergram#1]
This is a solid project!

I would be very interested in working on the camera element - filters etc.

Did you implement pagination?

Did you implement a custom camera implementation?

**Comment by mdanics** [comment]
@Joshgallagher 
Thank you! This is my first big project so the kind words really mean a lot.

Working on the camera / filter element would be awesome. I recall [Dart Image](https://github.com/brendan-duncan/image) having the best image editing options. In the [examples](https://github.com/brendan-duncan/image/wiki/Examples) there was changing an image to greyscale, and I believe there were ways to manipulate the image that we could save to 'presets' that the user could select, in a UI like Instagram. 

Currently no pagination has been implemented. On all pages, it will query all documents in the collection.   

For the camera implementation, I am currently on the simple route. Using the [image picker](https://github.com/flutter/plugins/tree/master/packages/image_picker) plugin. It was on my roadmap to make a custom camera / image selection UI like the real instagram using the [camera plugin](https://github.com/flutter/plugins/tree/master/packages/camera), but also I haven't gotten to that. If you were interested in that, it would be really cool.

Thanks again, I really appreciate you checking out this project!

**Comment by mdanics** [comment]
@Joshgallagher Would you be interested in working on any of them?

**Comment by josh9060** [comment]
I'd definitely be interested - I'll have to fit it in around work. I'm mostly interested in the camera - building out a powerful Flutter experience.

**Comment by mdanics** [comment]
Awesome, looking forward to some PRs!

**Comment by mdanics** [comment]
@Joshgallagher 
There's a new plugin [image cropper](https://github.com/hnvn/flutter_image_cropper) which looks like it could be useful.
