### ISSUE TITLE
Sorting posts on Feed by timestamp

### ISSUE THREAD

**Issue by kennethqw** [mdanics/fluttergram#100]
The Fluttergram app looks great and is working on both android and ios devices. From issue #54 I was able to sort the posts according to timestamp.

However, I realized when I follow multiple users, all posts of a user will be displayed before all posts of another user is display.
For instance, if I follow UserA and UserB, all the posts of UserA will appear before all the posts of UserB regardless if UserA and UserB posted a content at the same time.

Can you please advice where I can make amendment to the code? Thank you in advance!

**Comment by Aashikr** [comment]
Read the timestamp for every image post, and sort it in feed.

**Comment by kennethqw** [comment]
@Aashikr Thank you for the reply, I've actually solved it by doing a sort before resulting the list!

**Comment by AlienSofts** [comment]
@kennethqw  can you share code how did you do that sorting please?
