### ISSUE TITLE
Stuck at login screen

### ISSUE THREAD

**Issue by jnash766** [mdanics/fluttergram#103]
I was finally able to get everything to build correctly and was able to get fluttergram to launch in my simulator and on my physical device.  Both locations prompted me to sign in with google, which I used an existing account and the authentication seemed to work correctly.  I do see the new userid show up in my Firebase instance.  But after that initial auth fluttergram appears to be frozen. I see the main splash page with the same "Sign in with Google" option, but I am unable to tap on that sign in anymore.  Force close the app and launch it again and it goes directly to the frozen screen.  Same exact results on using the simulator and my iphone.  I'm honestly not sure where to start with this issue, any suggestions?
Thank you!

------
![PNG image](https://user-images.githubusercontent.com/35532573/93487409-db076a80-f8ca-11ea-814a-6a7227c2ffde.png)

**Comment by mdanics** [comment]
Hm.. It's pretty hard to diagnose this issue with what you've provided. 

Did you correctly [set up firebase authentication](https://github.com/mdanics/fluttergram#3-setup-the-firebase-app)?

**Comment by jnash766** [comment]
I found this message, which seems related?  But can't seem to find that file anywhere?
![Screen Shot 2020-09-17 at 9 55 57 AM](https://user-images.githubusercontent.com/35532573/93780643-07cec100-fbee-11ea-9501-3c968f895e64.png)

**Comment by mdanics** [comment]
Maybe try running flutter clean and then re pod installing and pub getting

**Comment by amitsingh6391** [comment]
When we try to login we stuck their

**Comment by mdanics** [comment]
@jnash766 @amitsingh6391 Are you both gettings this on iOS only?

**Comment by jnash766** [comment]
The clean and pod install get steps took care of the file not found issue, but still having the issue stuck at login screen.  I haven't tried running on Android at all yet.

**Comment by mdanics** [comment]
@jnash766 any new errors now that you've resolved the file not found error?

**Comment by tilakpatel22** [comment]
@jnash766 @amitsingh6391 delete the googlesign code and then remake the code u will get a clear understanding also as well as it will work I don't know about the error much but I was facing same problem in my app then after I had rebuild whole google sign function and that's seems to work for me 🙂...

**Comment by makemagik** [comment]
I'm having the same issue.

I was able to click on the button, login using a google account, but after that it brings me to the same homepage. When I re-click, it just crashes.

@12tilak34 what do you mean by delete and remake the code? Care to give your working code in example? Thanks!

**Comment by mdanics** [comment]
Should be fixed in https://github.com/mdanics/fluttergram/commit/97c31603fcbad574fa292d373bd0de953883d3bd

If you could pull and double-check that this has fixed it in your environment, that would be great

**Comment by mdanics** [comment]
Feel free to reopen this or create a new issue if this persists, but from my understanding this has been fixed
