### ISSUE TITLE
APK Not Opening on my Android

### ISSUE THREAD

**Issue by shaadart** [mdanics/fluttergram#107]

**Comment by iAkashPattnaik** [comment]
Try changing device..

**Comment by mdanics** [comment]
Need some more details in order to help you with this. 

What device? What error are you getting?

**Comment by iAkashPattnaik** [comment]
By the way, Its not working on any devices...
I Used Devices with API level 22 and 30 And Nothing Worked..

Seems Error in Old Build...

**Comment by mdanics** [comment]
@BLUE-DEVIL1134  thanks for bringing this to my attention.

I'm unable to reproduce this. Where are you facing this error? Using the release APK include din the repo? or are you trying to build? 

Can you provide any logs?

If you are trying to build, are you using the latest version? I just updated the app for Flutter 2 yesterday

**Comment by iAkashPattnaik** [comment]
Oh, We all know that Flutter 2 is a significant change...
When I downloaded the release apk from readme.md it didn't installed And I haven't tried to build till now but as you are telling, I will try today and tell ...
