### ISSUE TITLE
how can we add music to our instagram stories

### ISSUE THREAD

**Issue by ASVKVINAYAK** [mdanics/fluttergram#109]
i am also wanted to make a app which adds music to whatsapp status just like instagram music 
but i am not able to get the information related to how to do it .
Can anyone suggest any flutter plugin so that we can convert image to video and then add music(from api like spotify ) just like we add music to our instagram stories

**Comment by mdanics** [comment]
Hi ASVKVINAYAK,

I would look at an audio player plugin, like https://pub.dev/packages/audioplayers that you can pragmatically play the audio with an image displayed. No need to convert the image to a video

At the moment this is out of the scope of Fluttergram, so I will be closing this issue.
