### ISSUE TITLE
Can I improve this project and use to teach Flutter for my students?

### ISSUE THREAD

**Issue by Dhciolfi** [mdanics/fluttergram#11]
Hi!

I'm an instructor and I have a course about app development with Flutter!

This project is really cool! I have downloaded it and modified a few parts so it's a little better now. 

I would like to use this project to teach Flutter for my students. Would be a problem for you? I will give the credits to you.

Thanks!

**Comment by mdanics** [comment]
I have no problem with you using it, just please include a link to the repo and credits like you said. 

If you have made changes, I would really appreciate it if you make some pull requests so that we can improve this project. 

Thanks!

**Comment by Dhciolfi** [comment]
Sure!

I'm still changing the project. When I finish, I will make the pull requests.

Thanks!

**Comment by mdanics** [comment]
Thanks!
