### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by TimMensch** [mdanics/fluttergram#110]
Grabbed a fresh clone, tried to build. Build error:

```
lib/upload_page.dart:50:13: Error: No named parameter with the name 'resizeToAvoidBottomPadding'.
            resizeToAvoidBottomPadding: false,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/Devel/flutter/packages/flutter/lib/src/material/scaffold.dart:1451:9: Context: Found this candidate, but the arguments don't match.
  const Scaffold({
        ^^^^^^^^
```

New to Flutter/Dart, so not loving the idea of needing to debug it? Thoughts?

**Comment by mdanics** [comment]
Fixed in https://github.com/mdanics/fluttergram/pull/111/commits/a75adfe4260bd90448a1650a0adbc7c7f994c0bc. Turns out `resizeToAvoidBottomPadding` was deprecated. 

Pull from master and it should be working.  Thanks for bringing this to my attention.
