### ISSUE TITLE
[Best Practice] Separate Logic Code from UI

### ISSUE THREAD

**Issue by Babwenbiber** [mdanics/fluttergram#115]
The UI really looks smooth and I think it is a great place to go especially for beginners.
Nevertheless, it might be somewhat missleading for them.
You have no separation of UI from the business logic and beginners will adapt that.
This is just my point of view, but I think this is one of the first GOTO repos for beginners and therefore you have a responsibility for that.

Let me know you think about it.
Cheers

**Comment by mdanics** [comment]
I completely agree. I added a disclaimer in the readme to be more transparent for beginners: https://github.com/mdanics/fluttergram/commit/d372cfd8e34994af5f774a25b3d4ae147d3965aa 

I have been wanting to rebuild this from the ground up with the current Flutter best practices, however, I haven't had the time. 

That said, PR's are welcome, so if you would like to help improve Fluttergram you can :)
