### ISSUE TITLE
How to make instagram explore screen ?

### ISSUE THREAD

**Issue by darmawan01** [mdanics/fluttergram#116]
Hi, have you implement the explore screen like instagram ?
it's so hard to create the grid view, with small one and big one. 

example:

![image](https://user-images.githubusercontent.com/23370707/122920032-7e723800-d393-11eb-9191-96deaf157a7e.png)

or myabe anyone have any idea for this ?

**Comment by mdanics** [comment]
This type of layout is called a Masonry Grid.  I would do some Googling to see how it can be implemented in Flutter. 

From a quick search, https://pub.dev/packages/flutter_staggered_grid_view looks like a promising package
