### ISSUE TITLE
Follow standards for screenshots in readme

### ISSUE THREAD

**Issue by paul-hammant** [mdanics/fluttergram#12]
1. open an issue, 
2. drag an image from your file system into the new-issue textbox
3. watch github make a URL for that in the `![...](...)` markdown style
4. copy that you your clipboard
5. paste it into the README, commit and push.
6. close that issue without submitting you'd started to make `3` above.

**Comment by paul-hammant** [comment]
Oh interesting ..... the README renders with images inline (GIF animation) for Chrome, but is a list of links only for Firefox (to .webm files in the GH repo which isn't allowed to be an image host itself)

**Comment by knightkhan** [comment]
Because Fluttergram depends on image 1.1.30 which requires SDK version >=1.0.0 <2.0.0, version solving failed.
pub get failed (1)

**Comment by mdanics** [comment]
Fixed
