### ISSUE TITLE
dependencies spec still valid?

### ISSUE THREAD

**Issue by ScottYelich** [mdanics/fluttergram#16]
I am having trouble trying to get the dependencies to work... looks like http is the start of the mess, but then it moves on to things like:

Running "flutter packages get" in fluttergram...                 
Because cached_network_image >=0.4.1 <0.4.2 depends on flutter_cache_manager ^0.1.1 and cached_network_image >=0.4.0 <0.4.1 depends on flutter_cache_manager ^0.1.0, cached_network_image >=0.4.0 <0.4.2 requires flutter_cache_manager ^0.1.0.
And because cached_network_image >=0.4.2 depends on flutter_cache_manager ^0.1.2 which depends on http ^0.11.3+14, cached_network_image >=0.4.0 requires http ^0.11.3+14.
So, because Fluttergram depends on both cached_network_image ^0.4.0 and http ^0.12.0, version solving failed.
 
pub get failed (1)

**Comment by ScottYelich** [comment]
started here:

flutter packages get
Running "flutter packages get" in fluttergram...                 
Because every version of flutter_test from sdk depends on http 0.12.0 and Fluttergram depends on http ^0.11.3+14, flutter_test from sdk is forbidden.
So, because Fluttergram depends on flutter_test any from sdk, version solving failed.
 
pub get failed (1)

**Comment by ScottYelich** [comment]
I'm doing this for now:  pubspec.yaml
See:  https://github.com/dart-lang/json_serializable/issues/241

dev_dependencies:
#  flutter_test:
#    sdk: flutter
  build_runner: "^1.0.0"

**Comment by mdanics** [comment]
Thanks for pointing this out, fixed it in the latest commit.

**Comment by ScottYelich** [comment]
thx.  I'll update and test in ~ 45 minutes ... feedback will appear here.  (I get crashes with taking a pic and hangs on pic upload, etc... not sure if it's related to versions/dependencies).   I'll keep checking.

**Comment by mdanics** [comment]
Kk thanks. Haven't a chance to investigate the other issues you opened, but will look at them soon.

**Comment by ScottYelich** [comment]
Confirmed working with no issues for me.  thx.

**Comment by mdanics** [comment]
It fixed #18 and #17 ?

**Comment by ScottYelich** [comment]
No.  To test #17 and #18 -- I have to make the firebase and other changes to the vanilla code.  I haven't had the chance to do that yet.  I expect #17 and #18 to still fail -- but I can't say either way until I test.  I did a second clone so I could keep the state of the old system as reference and work to correct in a separate place.  I'll try to update by EOD tomorrow.
