### ISSUE TITLE
Post?

### ISSUE THREAD

**Issue by ScottYelich** [mdanics/fluttergram#18]
Pressing the (+) on Fluttergram iOS (iOS12):

Please audit all existing usages of Date when you enable the new behavior. In a future release, the behavior will be changed to the new behavior, so if you do not follow these steps, YOUR APP MAY BREAK.
[VERBOSE-2:shell.cc(182)] Dart Error: Unhandled exception:
inheritFromWidgetOfExactType(_LocalizationsScope) or inheritFromElement() was called before _Uploader.initState() completed.
When an inherited widget changes, for example if the value of Theme.of() changes, its dependent widgets are rebuilt. If the dependent widget's reference to the inherited widget is in a constructor or an initState() method, then the rebuilt dependent widget will not reflect the changes in the inherited widget.
Typically references to to inherited widgets should occur in widget build() methods. Alternatively, initialization based on inherited widgets can be placed in the didChangeDependencies method, which is called after initState and whenever the dependencies change thereafter.
#0      StatefulElement.inheritFromElement.<anonymous closure> (package:flutter/src/widgets/framework.dart:3877:9)
#1      StatefulElement.inheritFromElement (package:flutter/src/widgets/framework.dart:3910:6)
#2      Element.inheritFromWidgetOfExactType (package:flutter/src/widgets/framework.dart:3261:14)
#3      Localizations.of (package:flutter/src/widgets/localizations.dart:444:47)
#4      debugCheckHasMaterialLocalizations.<anonymous closure> (package:flutter/src/material/debug.dart:88:23)
#5      debugCheckHasMaterialLocalizations (package:flutter/src/material/debug.dart:127:4)
#6      showDialog (package:flutter/src/material/dialog.dart:606:10)
#7      _Uploader._selectImage (file:///NOBACKUP/fluttergram/lib/upload_page.dart:77:12)
<asynchronous suspension>
#8      _Uploader.initState (file:///NOBACKUP/fluttergram/lib/upload_page.dart:28:7)
#9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3787:58)
#10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
#11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
#13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796:14)
#14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
#16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
#17     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
#18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
#19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
#20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
#22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796:14)
#23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
#25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796:14)
#26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
#28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
#29     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
#30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
#31     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
#32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
#33     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
#34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
#35     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
#36     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
#37     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
#38     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3993:11)
#39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
#41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
#42     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
#43     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
#44     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805:11)
#45     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
#46     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
#47     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
#48     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:996:36)
#49     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:981:20)
#50     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2253:19)
#51     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:974:11)
#52     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:256:23)
#53     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1727:58)
#54     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:796:15)
#55     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1727:13)
#56     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:245:5)
#57     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:323:5)
#58     RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:169:12)
#59     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
#60     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:405:13)
#61     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1320:12)
#62     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1238:20)
#63     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1506:7)
#64     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:765:18)
#65     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
#66     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:671:13)
#67     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
#68     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
#69     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
#70     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
#71     _invoke (dart:ui/hooks.dart:139:13)
#72     _drawFrame (dart:ui/hooks.dart:128:3)

...

**Comment by mdanics** [comment]
Is this a dup of #17

**Comment by mdanics** [comment]
Just fixed #17 

Please try pulling the repo and let me know if that also fixes this.

**Comment by mdanics** [comment]
Closing because I cant replicate and believe it was fixed. Please reopen if it's still happening.
