### ISSUE TITLE
Error regarding dependencies after updating flutter SDK

### ISSUE THREAD

**Issue by harshapulikollu** [mdanics/fluttergram#19]
After using the latest dependencies and new flutter update, I'm getting this error when I try to run "packages get" in android studio.
```
Because every version of flutter_test from sdk depends on http 0.11.3+17 and mercury depends on http ^0.12.0, flutter_test from sdk is forbidden.
So, because mercury depends on flutter_test any from sdk, version solving failed.

pub get failed (1)
```

**Comment by mdanics** [comment]
Im pretty sure this is the same as #16 and was fixed.

Can you make sure you have the latest version of the repo and try it again and let me know the results?

Thanks

**Comment by harshapulikollu** [comment]
yes, it fixed the issue. Thanks.
