### ISSUE TITLE
Amazing work man

### ISSUE THREAD

**Issue by shock-wave007** [mdanics/fluttergram#2]
it would be awesome if u can create a youtube series just EXPLAINING your code what function does what it will help non flutter developer to understand your code and i know creating tutorial series is not so easy so just explain as i am a native android developer and trying to create something similar

**Comment by mdanics** [comment]
Hey, thank you.
Unfortunately I don't see my self making a YouTube series for this. 

Feel free to ask me what certain functions do, and I'd be happy to explain

**Comment by shock-wave007** [comment]
have thought of how u gonna structure your data (block person cant seen post, if private account only followers can view post and public account anyone can view post).

if u have can u post some screenshot of firestore and json file from realtime database with rules

or any other way you can expain

**Comment by mdanics** [comment]
I haven't put huge thought into making private and non private accounts, and I'm not sure if I'm going to implement that as it doesn't really provide much more _different_ functionality. 

As of now, there are no rules for the firestore. That has been something that I haven't been able to understand and I haven't had the time to dedicate myself to make them with a high standard. It is definitely on my radar though.

**Comment by shock-wave007** [comment]
If you got time we can discuss on that we might get some solutions 😅😅

**Comment by mdanics** [comment]
Yeah I've got time, that'd be awesome. Do you have any ideas / experience with firebase security rules?
