### ISSUE TITLE
Cloud functions code for notifications for like, comment, etc..

### ISSUE THREAD

**Issue by harshapulikollu** [mdanics/fluttergram#20]
I want to propose a new enhancement(feature sort of). please try to add code in cloud functions such that it will trigger for every change  like, comment and other things in firestore DB and send notification with payload to respective users.

**Comment by mdanics** [comment]
Nice idea for an enhancement, thanks. I don't think I will work on implementing this as I don't have time, but I don't think it would be too difficult to do ([basic example](https://firebase.google.com/docs/cloud-messaging/admin/send-messages)). I recommend exploring adding it yourself, and would appreciate it if you submit a PR if you end up getting to it.

**Comment by mdanics** [comment]
Had some time, and implemented it. Download the most recent apk to try it out.
