### ISSUE TITLE
A cloud functions typo in readme.md file

### ISSUE THREAD

**Issue by harshapulikollu** [mdanics/fluttergram#21]
In 3rd point under set up firebase app,
you have written the last point as **Replace the url in the `_getFeed` function in `upload_page.dart` with your cloud function url from the previous step.**
but the function `_getFeed` is presented in `feed.dart` file not in `upload_page.dart`

**Comment by mdanics** [comment]
Thank you for pointing this out!

Other than this, were you able to successfully build Fluttergram?

**Comment by harshapulikollu** [comment]
yes, I'm able to build it without other issues.

**Comment by Isonomic** [comment]
can you explain how to do this? I am stuck on this step. Do i type this on the command line or something Push the function getFeed with firebase deploy --only functions In the output, you'll see the getFeed URL, copy that.........Like it says push the function getFeed. How do I push this. Thanks for helping a newer and slowly learning dev guys
