### ISSUE TITLE
Continue and please upgrade this particular issu

### ISSUE THREAD

**Issue by arafat1971** [mdanics/fluttergram#22]
Improve Caching of Profiles, Images, Etc.
    Notificaitons for likes, comments, follows, etc
    Better post creation, add filters to your image
    Custom Camera Implementation
    Animations (heart when liking image)
    Firebase Security Rules
    Delete Posts
    Registration without Google SignIn
    Direct Messaging
    Stories
    Clean up code

**Comment by mdanics** [comment]
Feel free do them and submit PRs to help improve Fluttergram. 

As for me, I feel as though Fluttergram is at a stage that I am happy with for now and will work on if I have time.
