### ISSUE TITLE
Failure [INSTALL_FAILED_NO_MATCHING_ABIS]

### ISSUE THREAD

**Issue by boreys** [mdanics/fluttergram#23]
I got this error when trying to install app-release.apk to my device for testing

Failure [INSTALL_FAILED_NO_MATCHING_ABIS]

**Comment by mdanics** [comment]
hm, just tried on my device and it worked. 

What device are you using?

**Comment by boreys** [comment]
Samsung Alpha with Android 5.0.2
I believe when you compile it, you need to enable ABI

check this out: https://stackoverflow.com/questions/36414219/install-failed-no-matching-abis-failed-to-extract-native-libraries-res-113

**Comment by mdanics** [comment]
[https://file.io/9d2tkF](https://file.io/9d2tkF) try this file

**Comment by boreys** [comment]
file not found

**Comment by mdanics** [comment]
https://ufile.io/1werv 

apologies

**Comment by boreys** [comment]
photo upload does not work, I got error when testing it. try to install the app and upload a photo.

**Comment by mdanics** [comment]
hm sorry, but I guess Fluttergram isn't compatible with older versions of Android. As fluttergram isn't a product, I personally won't be putting more time into trying to support older devices. Sorry. 
By all means, fork the project try to get it to run on your device, if you're successful a PR would be great.
