### ISSUE TITLE
Would you be so kind to add a license to your project?

### ISSUE THREAD

**Issue by fiuser** [mdanics/fluttergram#24]
I think it would be nice to add a license to the project, u can get more info here:

https://help.github.com/articles/licensing-a-repository/

Keep it up and good job,

**Comment by mdanics** [comment]
Added

**Comment by fiuser** [comment]
Thank you to add it. But please check this link:

https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

From the previous link:
Unlike software-specific licenses, CC licenses do not contain specific terms about the distribution of source code,..

This site maybe can help you:

https://choosealicense.com/
