### ISSUE TITLE
How to show a Map values in listview 

### ISSUE THREAD

**Issue by harshapulikollu** [mdanics/fluttergram#26]
As you know user's following and followers are in Map data type, I want to know how can we show them in listView with their username and display image just like we are doing in search...
**Scenario:** 
![screenshot 72 _li](https://user-images.githubusercontent.com/22256553/47789818-a5d7ea80-dd3b-11e8-81ff-a1b7ddde1ccf.jpg)
> When we click on either followers or following _(which shows numbers above FOLLOW/UNFOLLOW button)_ in user profile page, It has to open a new page and shows all following/followers list with their name and display name. 

I tried as much as I can but can't get that work, Please help me on this to work, because of this I'm unable to
work ahead on my other project also which uses the same map stuff.

**Comment by mdanics** [comment]
Were you able to solve this?

**Comment by harshapulikollu** [comment]
I guess i did solved it but Donno whether it's a effective way to do it or not.

**Comment by harshapulikollu** [comment]
I'm getting only any one user through the way I implemented. Can you help to find out a way to get all following and followers.

**Comment by mdanics** [comment]
The way I would do it is: 
- we have a map of the followers/following
  - get the userIds from the map as a list
- loop through the list of userIds and call to firebase to get the user info
- display the list of users

btw I would love it if you create PRs for some of the features you've been adding to mercury, like location when posting, messaging, etc

**Comment by harshapulikollu** [comment]
I did it using a cloud function http trigger with user ID as a query string it will fetch as users and show the list to user. I'm thinking to release mercury so once I'm done with it all and release it to play/app store then I'll create a PR.

**Comment by harshapulikollu** [comment]
I did it using a cloud function HTTP trigger with userID as a query string(like **http://uscentral.projectname.functions.net/getFollowing?uid=_userId_**  it will fetch all following users and show the list to user. I'm thinking to work on this more sure ASAP I'll create a PR and contribute to this repo.

**Comment by mdanics** [comment]
Awesome, thank you! look forward to reviewing them :)
