### ISSUE TITLE
Loading Feed Errors?

### ISSUE THREAD

**Issue by 0x13ens** [mdanics/fluttergram#3]
On the home button screen, I just have the Appbar and a loading circle and on the profile below the tabs it's just loading endlessly any ideas? nice work btw 

![home](https://user-images.githubusercontent.com/31564553/41207580-69a175cc-6d10-11e8-98ed-09b23fbbac15.png)
![profile](https://user-images.githubusercontent.com/31564553/41207582-6d98baf0-6d10-11e8-9631-58e4e91b561e.png)

**Comment by mdanics** [comment]
Is from my APK or did you clone and build your own?

**Comment by 0x13ens** [comment]
Hey mdanics, I followed the instructions built and cloned my own, so far I can register successfully, see the new posts in the google console, however, these feeds just don’t seem to want to load in the actual app

**Comment by mdanics** [comment]
Hey, 

For the main Feed, did you upload my cloud function to your console, and then replace the url on line 83 in [feed.dart ](https://github.com/mdanics/fluttergram/blob/master/lib/feed.dart)
`https://us-central1-mp-rps.cloudfunctions.net/getFeed` with your own link? ensuring `?uid=` is still there?
That would be my initial guess for it to not load properly.

The user profile, however, is more interesting as that should work regardless of cloud functions. 
Maybe Firebase isn't working on your clone for some reason.
If you use the search page and search for your username, does it return results?

**Comment by 0x13ens** [comment]
Hey, thanks again, I did double/triple check the url and it seems to be correct following your format. The search user page does indeed return results

**Comment by mdanics** [comment]
Hm... 
Can you post a photo of your cloud functions dashboard? 

Also try visiting the link with your user id (assuming you are following people with posts). For instance, for me visiting my url with my userid I get: [this response](https://us-central1-mp-
rps.cloudfunctions.net/getFeed?uid=110640536142883096796), showing there is data.

**Comment by 0x13ens** [comment]
Hey, dude, I tried making new instances and such and still the same I believe I got a response, however, I've just done a full hard reset and will be trying from fresh again tonight! Have you got a contact other then here I could quickly run issues by you? Thanks
