### ISSUE TITLE
feed url does not show

### ISSUE THREAD

**Issue by and1990** [mdanics/fluttergram#30]
Hi, guys.
I have faced a problem when I built fluttergram.

After I deployed my functions, the console didn't show feed url, the log is:
```
~/firebase  firebase deploy --only functions

=== Deploying to 'fluttergram-ae7fd'...

i  deploying functions
Running command: npm --prefix "$RESOURCE_DIR" run lint

> functions@ lint /Users/liutengfei/firebase/functions
> tslint --project tsconfig.json


WARNING: /Users/liutengfei/firebase/functions/src/index.ts[1, 1]: 'functions' is declared but its value is never read.

Running command: npm --prefix "$RESOURCE_DIR" run build

> functions@ build /Users/liutengfei/firebase/functions
> tsc

✔  functions: Finished running predeploy script.
i  functions: ensuring necessary APIs are enabled...
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...

✔  Deploy complete!

Project Console: https://console.firebase.google.com/project/fluttergram-ae7fd/overview
```

**Comment by harshapulikollu** [comment]
Hi, in most of the cases your feed url should be "

> https://storage-location-project-name-in-firebase-console.cloudfunctions..net/getFeed"

for example it can be like shown below
> https://us-central1-flutterggram.cloudfunctions.net/getFeed?uid=_userID_

where userID is passed dynamically.

**Comment by mdanics** [comment]
@and1990 Were you able to get it working with @harshapulikollu's comment?

**Comment by and1990** [comment]
@mdanics Hi, sorry for reply late. 
Actually, I don't figure out what he said. When I ran 'firebase deploy --only functions' command, the console didn't show some URLs like the 'getFeed' URL. What should I do?

**Comment by mdanics** [comment]
If you log in to firebase and click the functions tab you can see the url which you can copy and paste.

<img width="800" alt="screen shot 2019-01-10 at 12 00 00 pm" src="https://user-images.githubusercontent.com/10066840/50984240-63ffb900-14cf-11e9-8da4-501f350fde91.png">

Let me know if this works

**Comment by mdanics** [comment]
@and1990 did you find the url?
