### ISSUE TITLE
Feed only works on Profile

### ISSUE THREAD

**Issue by amizanali** [mdanics/fluttergram#31]
First of all, this is a great project. So far I manage to build the app but there is a slight roadblock on the feed.

So far it only works on Profile, but the feed does not load on Home. 

Am I missing something?

**Comment by mdanics** [comment]
Have you created your firebase function and changed the url in `feed.dart`?

**Comment by amizanali** [comment]
Surprisingly after rebuilding the app, and following another user, the Home starts to show the posts from the other user.

**Comment by mdanics** [comment]
Oh haha that makes perfect sense. The feed consists of posts of users that you follow, and so not following anyone will result in an empty feed. 

I guess there should be a message in-place of the feed notifying the user that they should follow people :)

**Comment by mdanics** [comment]
I actually made it so you can see your own posts with [this commit](https://github.com/mdanics/fluttergram/commit/69b5d69bc5f2d6f51c3deb2bdbb863977fdadf49)

**Comment by mdanics** [comment]
Forgot to mention that this will only take action for newly made accounts
