### ISSUE TITLE
alert dialog box

### ISSUE THREAD

**Issue by mishubham** [mdanics/fluttergram#32]
the argument type Context cant be assign to parameter type BuildContext error in alert dialog box

  return showDialog<Null>(
    context: context,         //here error
      barrierDismissible: false, // user must tap button!

**Comment by mdanics** [comment]
When are you getting this error?

**Comment by mishubham** [comment]
getImage() async {
    return showDialog<Null>(
      context: this.context,                                           //i'm solve this error by putting this.context
      builder: (BuildContext context) {
        return new SimpleDialog(
          title: const Text('Create a Post'),
          children: <Widget>[
            new SimpleDialogOption(
                child: const Text('Take a photo'),
                onPressed: () async {
                  Navigator.pop(context);
                  var tempImage =
                  await ImagePicker.pickImage(source: ImageSource.camera);
                  setState(() {
                    sampleImage = tempImage;
                    filename = basename(sampleImage.path);
                  });
                }),
            new SimpleDialogOption(
                child: const Text('Choose from Gallery'),
                onPressed: () async {
                  Navigator.of(context).pop();
                  var tempImage =
                  await ImagePicker.pickImage(source: ImageSource.gallery);
                  setState(() {
                    sampleImage = tempImage;
                    filename = basename(sampleImage.path);
                  });
                }),
            new SimpleDialogOption(
              child: const Text("Cancel"),
              onPressed: () {
                Navigator.pop(context);
              },
            )
          ],
        );
      },
    );
  }




  //i'm solve this error by putting this.context

**Comment by mdanics** [comment]
What OS are you experiencing this for?

**Comment by mishubham** [comment]
ubuntu

**Comment by mdanics** [comment]
Sorry, I meant iOS or Android?

**Comment by mishubham** [comment]
android

**Comment by mdanics** [comment]
After looking into this further, the sample code you provided is not code from Fluttergram. 

The most similar function I could find is `_selectImage()` in `upload_page.dart` which is as follows

```
_selectImage() async {
    return showDialog<Null>(
      context: context,
      barrierDismissible: false, // user must tap button!

      builder: (BuildContext context) {
        return new SimpleDialog(
          title: const Text('Create a Post'),
          children: <Widget>[
            new SimpleDialogOption(
                child: const Text('Take a photo'),
                onPressed: () async {
                  Navigator.pop(context);
                  File imageFile =
                      await ImagePicker.pickImage(source: ImageSource.camera);
                  setState(() {
                    file = imageFile;
                  });
                }),
            new SimpleDialogOption(
                child: const Text('Choose from Gallery'),
                onPressed: () async {
                  Navigator.of(context).pop();
                  File imageFile =
                      await ImagePicker.pickImage(source: ImageSource.gallery);
                  setState(() {
                    file = imageFile;
                  });
                }),
            new SimpleDialogOption(
              child: const Text("Cancel"),
              onPressed: () {
                Navigator.pop(context);
              },
            )
          ],
        );
      },
    );
  }
```
Which works without any issues.

**Comment by mishubham** [comment]
ok thx
