### ISSUE TITLE
bottom navigation bar

### ISSUE THREAD

**Issue by orazz** [mdanics/fluttergram#33]
How to set bottom navigation bar always on the bottom?

**Comment by mdanics** [comment]
In what scenarios is it not on the bottom? From my understanding it's always on the bottom?

**Comment by orazz** [comment]
I mean when clicking to the post it's opening new page and bottom navigation disappear

**Comment by mdanics** [comment]
Oh, that would require some restructuring of the code. Unfortunately this is not something I have time for now, however if you do end up doing it a PR would be greatly appreciated.
