### ISSUE TITLE
getFeed.js returns no data : []

### ISSUE THREAD

**Issue by didiosn** [mdanics/fluttergram#35]
Hi, this is awesome project. I've cloned it, follow steps, creates indexes. All pages are now working except the home page, which display data returned by getFeed.js. I've tried to see, in my browser with url, if something is returns : YES I have a result by empty one. But I have 3 posts from 2 different users. 

Any ideas ?

Thanks

**Comment by mdanics** [comment]
Are you following the users with the posts? 

The getFeed function only returns posts from people you follow as to mimic the social media experience.

**Comment by didiosn** [comment]
Yes, sure... You're right, I forgot to follow users. Now it's full working. 
getFeed.js query can be done with a normal firebase query on insta_posts, I guess, why did you choose an external function?

**Comment by mdanics** [comment]
Glad you got it working!

For making it an external function, I guess it felt more conventional to have an an API call pull in the results for the feed rather than locally querying. Also if the database becomes heavily populated, it would be preferred to have the processing happen not locally, as it would slow the device down. Lastly this architecture would allow for customization of how the feed is made without requiring the app to be updated.

**Comment by GustavoContreiras** [comment]
I'm receiving some errors that causes empty feed even following other users:
I/flutter ( 7793): Error getting a feed:
I/flutter ( 7793): Http status 500

Does anybody knows how to solve?

**Comment by mdanics** [comment]
@GustavoContreiras What are the logs in the firebase console?

**Comment by GustavoContreiras** [comment]
Thanks for the fast answer. That happened because I forgot these steps:
```
Push the function getFeed with firebase deploy --only functions In the output, you'll see the getFeed URL, copy that.
Replace the url in the _getFeed function in feed.dart with your cloud function url from the previous step.
```
I was going to edit my last comment.

Nice project!

**Comment by mdanics** [comment]
Awesome, glad you figured it out!

**Comment by mdanics** [comment]
@didiosn I actually made it so you can see your own posts with [this commit](https://github.com/mdanics/fluttergram/commit/69b5d69bc5f2d6f51c3deb2bdbb863977fdadf49)

**Comment by mdanics** [comment]
Forgot to mention that this will only take action for newly made accounts

**Comment by akiiii29** [comment]
> Thanks for the fast answer. That happened because I forgot these steps:
> 
> ```
> Push the function getFeed with firebase deploy --only functions In the output, you'll see the getFeed URL, copy that.
> Replace the url in the _getFeed function in feed.dart with your cloud function url from the previous step.
> ```
> 
> I was going to edit my last comment.
> 
> Nice project!

im follow these steps and still got this error. Any advise ?
