### ISSUE TITLE
Feed should display your own photos too

### ISSUE THREAD

**Issue by GustavoContreiras** [mdanics/fluttergram#38]
The original app shows the photos you posted on your news feed.

**Comment by mdanics** [comment]
You're right, I think what happened was I had followed myself through the firebase console for debugging purposes, but I think it's good for developers to be able to see their posts in the feed without having to make multiple accounts.

Added it with [this commit](https://github.com/mdanics/fluttergram/commit/69b5d69bc5f2d6f51c3deb2bdbb863977fdadf49)

**Comment by mdanics** [comment]
Forgot to mention that this will only take action for newly made accounts
