### ISSUE TITLE
WebP Images

### ISSUE THREAD

**Issue by threeseed** [mdanics/fluttergram#4]
WebP is only supported in Chrome. So we can't see the preview images on iOS or OSX.

Maybe switch to GIF ?

**Comment by mdanics** [comment]
I tried converting them to GIF's and the file size rocketed. 

Any tools you recommend for gif conversion?

**Comment by IvoryAguado** [comment]
If there are icons use SVG, for images you should compress them or maybe download them on the first install of the app from a CMS could be interesting.

**Comment by mdanics** [comment]
Won't convert previews to GIFs as they are too large and will increase the repo size.

**Comment by mdanics** [comment]
Updated readme to use gifs, hosting the gifs outside of the repo
