### ISSUE TITLE
Username textfield goes blank on the first try to register

### ISSUE THREAD

**Issue by GustavoContreiras** [mdanics/fluttergram#40]
### Reproducing
- Clean database users and authentications
- Delete app from emulator
- Run application
- Login with google account
- Write username
- Press next or confirmation on keyboard
- Username field will erase
- Write again
- Press next or confirmation on keyboard
- Username will be accepted and you will be redirected

Debug console: https://pastebin.com/XSe6RReT

**Comment by mdanics** [comment]
Do you know if this still happens when running the app in production?

**Comment by gregology** [comment]
I had this same experience with the APK from.the readme on my Essential PH-1 running Android Pie.

**Comment by mdanics** [comment]
Kk I'll look into it in the next few days

**Comment by GustavoContreiras** [comment]
My solution for that was removing the "create username screen" and generate a username automatically on the first login with display name and random number.

Here is my signInWithGoogle function:
```
@override
  Future<String> signInWithGoogle() async {

    print('[Auth] [signInWithGoogle] START');

    GoogleSignInAccount googleUser = await _googleSignIn.signIn();
    GoogleSignInAuthentication googleAuth = await googleUser.authentication;
    final FirebaseUser user = await _firebaseAuth.signInWithGoogle(idToken: googleAuth.idToken, accessToken: googleAuth.accessToken);

    updateUserData(); //creates basic data like displayName, isEmailVerified, etc

    DocumentReference _documentReference = _firestore.collection('users').document(user.uid);

    _documentReference.get().then((DocumentSnapshot docSnapshot) {

      if (docSnapshot.exists) {
        if (docSnapshot['username'] == null) { //username == null on first login
          _generateUsername(); //generates an username and store on database
        }
        else {
          print('docSnapshot["username"] != null'); 
        }
      }
      else {
        print('[Auth] [signInWithGoogle] docSnapshot == null');  
      }
    });
    return user?.uid;
  }
```

**Comment by mdanics** [comment]
Awesome thanks @GustavoContreiras 

I've found what's causing the bug, but in fixing it I've created more bugs (classic lol). I'll let you know when I've made progress

**Comment by GustavoContreiras** [comment]
Easy solution: https://github.com/mdanics/fluttergram/pull/47/commits/542bb7c643b81012920a85f28367173823eead88

**Comment by mdanics** [comment]
Hey guys sorry for the delay, got busy with exams.

I appreciate the solution @GustavoContreiras, but I'm not a fan of the random numbers so I did some more digging and I think I fixed it with [this commit](https://github.com/mdanics/fluttergram/commit/4c247c64a9b6aad3cc90ae5d59fcfc3605489e54). 

havent updated the apk, but if you pull master and still face this bug, please let me know and I will reopen the issue

**Comment by GustavoContreiras** [comment]
Your project, your rules haha.

But in both ways we gotta check if the username already exists.

I'm using this code to check it but I'm not sure if that's right:

```
while (_keepGenereating) {

    int _tries = 0;

    print('[CurrentUser] [SignInWithGoogle] generating username');
    
    // Generates an username
    _username = _firebaseUser.displayName.toString().replaceAll(RegExp(r"\s+\b|\b\s"), "").toLowerCase().trim() + Random().nextInt(1000000).toString();
    _username = _firebaseUser.displayName.toString().replaceAll(RegExp(r"\s+\b|\b\s"), "").toLowerCase().trim().substring(0, 5) + 
      DateTime.now().year.toString() + DateTime.now().month.toString() + DateTime.now().day.toString() + DateTime.now().hour.toString() +
      DateTime.now().minute.toString() + DateTime.now().second.toString() + DateTime.now().millisecond.toString();

    // Checks if username already exist
    QuerySnapshot _querySnapshot = await _firebaseUsersCollectionRef.where('username', isEqualTo: _username).getDocuments();

    if (_querySnapshot.documents == null) {
      _keepGenereating = false;
    }
    else {
      print('[CurrentUser] [SignInWithGoogle] _querySnapshot.documents: ${_querySnapshot.documents}');
      if (_querySnapshot.documents.isEmpty) {
        print('[CurrentUser] [SignInWithGoogle] _querySnapshot.documents.isEmpty == true');
        _keepGenereating = false;
      }
      else {
        print('[CurrentUser] [SignInWithGoogle] _querySnapshot.documents.isEmpty == false');
        if (_querySnapshot.documents.length == 0) {
          print('[CurrentUser] [SignInWithGoogle] _querySnapshot.documents.length == 0');
          _keepGenereating = false;
        }
        else {
          print('[CurrentUser] [SignInWithGoogle] _querySnapshot.documents.length != 0');
          print('[CurrentUser] [SignInWithGoogle] _querySnapshot.documents.first: ${_querySnapshot.documents.first}');
        }
      }
    }

    _tries++;
    print('[CurrentUser] [SignInWithGoogle] _username: $_username, _keepGenereating: $_keepGenereating, _tries: $_tries');
  }
```

**Comment by mdanics** [comment]
Haha thanks appreciate all the help you've given with Fluttergram 

I'll look into implementing unique usernames, however I believe there aren't any places where fluttergram actually requires unique usernames as users are only referenced by their id. Nonetheless, unique usernames would be more _instagramy_ so it could be worthwhile
