### ISSUE TITLE
Home page interface dont save likes when switching pages

### ISSUE THREAD

**Issue by GustavoContreiras** [mdanics/fluttergram#44]
## Reproducing
- Like a photo on the home page
- Likes counter will increase and hearth will be coloured
- Switch pages
- Go back to home page
- Likes counter will reset and hearth will discolour
- The firebase database insta_posts will have the like saved

**Comment by mdanics** [comment]
Thanks for pointing this out, state wasn't being persisted on any of the tabs. Fixed.
