### ISSUE TITLE
Instagram-clone 

### ISSUE THREAD

**Issue by kamami** [mdanics/fluttergram#49]
I did not know where to post this, so I just thought it would be a goog idea to open a new issue.

https://github.com/mohak1283/Instagram-Clone

Did you guys see this? Any thoughts on it? I tested it and it is a exact clone of this project here, except it has some more features like chat, etc.

**Comment by GustavoContreiras** [comment]
The code looks cleaner, I'll use it to check if I'm doing things right on my custom fluttergram.
Anyway, I don't know how licenses work but the mdanics fluttergram has one: https://github.com/mdanics/fluttergram/blob/master/LICENSE

**Comment by mdanics** [comment]
Yes I saw it, and considering the read me is a straight copy of mine it seems he has taken a lot of _inspiration_ from this project, while cleaning up code and adding features.
