### ISSUE TITLE
Timestamps being set wrong

### ISSUE THREAD

**Issue by GustavoContreiras** [mdanics/fluttergram#54]
I think you are setting timestamps wrong in almost everything stored on Firestore.

https://github.com/mdanics/fluttergram/search?q=timestamp&unscoped_q=timestamp

If you post `"timestamp": DateTime.now().toString(),` it will save just a **String** and if you want to do some query with that it will require more steps than necessary.

But if you post `"timestamp": DateTime.now()` it will save a **Timestamp** type.

![image](https://user-images.githubusercontent.com/38460351/58216522-46d8c380-7cd5-11e9-951a-c5333bebb47f.png)

Maybe that's the reason some methods are returning things out of order.

**Comment by mdanics** [comment]
Ah yes, this was another limitation of Firebase at the time of writing Fluttergram. There was no true date-time support. 

I'll get on fixing this and the other workarounds for the old firebase

**Comment by mdanics** [comment]
Fixed in 
https://github.com/mdanics/fluttergram/commit/d7a227533fe4a701f79ade82e7de1476aae486c0
and
https://github.com/mdanics/fluttergram/commit/7e8625923d0be745d3b4fd5796ace5a50fd8018f
