### ISSUE TITLE
No visible @interface for 'FIRInstanceID' declares the selector 'token'

### ISSUE THREAD

**Issue by jaynelim** [mdanics/fluttergram#57]
build fails because getting error in FirebaseMessagingPlugin.m.
the error is generated from line 176. 
here's the code on line 176:

[_channel invokeMethod:@"onToken" arguments:[[FIRInstanceID instanceID] token]];

using legacy system.
any solutions?
thanks.

**Comment by mdanics** [comment]
I will take a look into this. What do you mean by legacy system?

**Comment by jaynelim** [comment]
hello i mean xcode legacy build system. because i was getting error like "Multiple commands produce '/build/ios/Debug-iphonesimulator/Runner.app..." and according to "https://github.com/flutter/flutter/issues/20685" i changed build system to legacy build system. 

the build was working after i made that change, until it threw the above error [_channel invokeMethod:@"onToken" arguments:[[FIRInstanceID instanceID] token]]; 

thanks for taking time from your busy schedule to look into this.

**Comment by SebastianBO** [comment]
Any update?

**Comment by mdanics** [comment]
Can you guys provide steps to reproduce?

**Comment by leitonet** [comment]
Did you guys solve this problem? any update? Thanks

**Comment by kdastan** [comment]
Same issue, any updates?

**Comment by mdanics** [comment]
@kdastan @leitonet How are you guys getting to this problem? I need steps to reproduce to be able to look into fixing it

**Comment by rajashekaranugu** [comment]
Am also getting same error. I was trying to integrate Firebase monitoring tool with ionic/codova App. Am following "https://firebase.google.com/docs/perf-mon/get-started-ios?authuser=0"

**Comment by leitonet** [comment]
I also had this problem using ionic but solved it using FirebaseX plugin.

**Comment by rajashekaranugu** [comment]
Hi @leitonet Thanks for the response is there any doc for migration from Firebase to FirebaseX

**Comment by leitonet** [comment]
@rajashekaranugu , I followed this:
https://github.com/dpa99c/cordova-plugin-firebasex

**Comment by mdanics** [comment]
@rajashekaranugu @leitonet This is a Flutter project, not Ionic

**Comment by leitonet** [comment]
I know @mdanics, just wanted to help @rajashekaranugu cause he is working with ionic.

**Comment by PramodJoshi** [comment]
I was receiving the exact error when trying to run my project on iOS 13 device (**worked fine on Android and iOS 12 devices**). And here is what helped me solve the issue:
- Changed **firebase_messaging: ^5.0.2** to **firebase_messaging: 5.0.0** in pubspec.yaml
- Did **pod update** in ios folder of the project
- Ran **flutter clean**

Hope this helps someone with similar issue.

**Comment by deatherving** [comment]
Same issue 2020, any updates?

**Comment by aihamakeel** [comment]
Just Add **@import FirebaseInstanceID;** in the header and it will work

**Comment by mdanics** [comment]
Closing due to irrelevancy + inactivity
