### ISSUE TITLE
Saving Longitude and Latitude coordinates as well

### ISSUE THREAD

**Issue by amizanali** [mdanics/fluttergram#59]
I'm trying to figure out how to save the longitudes and latitudes of the location chosen by user into the database as well.

**Comment by mdanics** [comment]
I would take a look at the `postToFireStore` function in [upload_page.dart](https://github.com/mdanics/fluttergram/blob/master/lib/upload_page.dart). That is where the posts are being saved. You can add any additional properties you want.
