### ISSUE TITLE
Sorting posts on Home page by timestamp

### ISSUE THREAD

**Issue by lockeygit** [mdanics/fluttergram#60]
Got the app working (on IOS), but posts on the main (homepage) are oldest-first, rather than newest-first as you'd expect from a social app.  Any way of changing the order?
I've tried various alternatives to the "orderBy("timestamp")" in getFeed.js which I guess is what's causing the issue (eg orderBy("timestamp","desc") but can't find one that works!!  (should add that at the moment, I'm the only registered user, so just seeing my own posts)

BTW In the 'Profile' section they are latest-first, but looks like they are pulled out in the wrong order and then reversed.

**Comment by mdanics** [comment]
I'm pretty sure that this is related with #54, once that's fixed i'll ensure that the feed is in the correct order

**Comment by lockeygit** [comment]
Yes, I've updated upload_page to "timestamp": DateTime.now() so that's saving correctly as a Timestamp. 
Issue with getFeed.js was that it needed an index (on ownerId & timestamp) for orderBy("timestamp","desc") to work, and it wasn't showing that as an error until I used firebase functions:log which gave me a link to create the necessary index - had tried to create one manually, but Firebase didn't seem to recognise it.
Feed now showing in the correct order anyway!

**Comment by mdanics** [comment]
Ah awesome, thanks for this. Really helpful. I'll try to make the docs clearer

**Comment by sumanabhi** [comment]
@lockeygit thanks for the posts of feed ordering but now the profile field is not coming in the same way.

**Comment by lockeygit** [comment]
You probably need to edit getPosts() in profile_page.dart then to change the orderBy or remove the .reversed
