### ISSUE TITLE
Image, 500 Error

### ISSUE THREAD

**Issue by Mika2709** [mdanics/fluttergram#63]
With the new Image version, it doesnt take the 500 anymore. Anyone knows a fix?

**Comment by mdanics** [comment]
This was fixed in #76 [(line)](https://github.com/mdanics/fluttergram/commit/d7a227533fe4a701f79ade82e7de1476aae486c0#diff-1cf5df05bd32351b59123db46157dc0bR157) as ImagePicker was updated to support built in compression
