### ISSUE TITLE
Compiler Error

### ISSUE THREAD

**Issue by jhb115** [mdanics/fluttergram#65]
I tried to run the program on my iOS simulator but I was getting this compiler issue. Do you know how to fix this problem?

I used `$ flutter run' command to run the code on the iOS simulator. 

Launching lib/main.dart on iPhone 8 Plus in debug mode...

Compiler message:
../../development/tools/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-0.7.0/lib/src/cached_network_image_provider.
dart:46:31: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type
'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart'
 ('../../development/tools/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (StringBuffer information) {
                              ^
Compiler failed on /Users/jeunghbyun/iOSProjects/fluttergram/lib/main.dart
Error launching application on iPhone 8 Plus.

**Comment by jhb115** [comment]
p.s. my visual studio code highlights the problem:

{
	"resource": "/Users/jeunghbyun/iOSProjects/fluttergram/lib/activity_feed.dart",
	"owner": "dart",
	"code": "must_be_immutable",
	"severity": 2,
	"message": "This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: ActivityFeedItem.mediaPreview, ActivityFeedItem.actionText",
	"source": "dart",
	"startLineNumber": 68,
	"startColumn": 7,
	"endLineNumber": 68,
	"endColumn": 23,
	"tags": []
}

**Comment by aloisogomes** [comment]
Hi, 
Open this file: **pubspec.yaml** 

replace
**cached_network_image: ^0.7.0**
to
**cached_network_image: ^1.1.3**
Save file, wait for updating packages, or rerun manually.

**Bonus tip:** You must place on your project **google.json**, it will link your project at google services like firebase /firestore, will avoid new compile errors.

If you not get it yet, follow this link:
[https://firebase.google.com/docs/flutter/setup](https://firebase.google.com/docs/flutter/setup)

Good coding!
