### ISSUE TITLE
couldn't deploy apk on different emulators

### ISSUE THREAD

**Issue by SekibOmazic** [mdanics/fluttergram#7]
Hi, I've tried to deploy the apk on different emulators but none of them worked. Also tried to download apk and install it to my old Nexus 5 - still no luck. Could you tell if there are any steps needed before just dragging apk to the emulator?

<img width="355" alt="screen shot 2018-06-22 at 11 03 59" src="https://user-images.githubusercontent.com/3735902/41770553-df6e964e-7612-11e8-8991-f6e64458d9c3.png">
<img width="753" alt="screen shot 2018-06-22 at 11 53 58" src="https://user-images.githubusercontent.com/3735902/41770593-0213d97a-7613-11e8-894a-403b186754c7.png">

Cool project btw ;-)

**Comment by mdanics** [comment]
Hm.. I haven't seen that error before. From some googling it looks like it might have to do with an sdk miss match between the emulator and the apk.

Do you have a real device to test the installation of the apk?

**Comment by SekibOmazic** [comment]
Yes, I tried on my old Nexus 5 device - without luck. At the end I built the source code on my own firebase instance.
