### ISSUE TITLE
Python Reactive Back End

### ISSUE THREAD

**Issue by billyrrr** [mdanics/fluttergram#72]
Hi, I am currently developing a new mobile back end [framework](https://github.com/billyrrr/flask-boiler) based on Firestore. I hope to use fluttergram as an example use case, so I plan to develop another version of back end using Python. I was wondering if a pull request of that is welcomed here. 

One of the new features that the new back end would achieve is the feed no longer has to be evaluated by cloud function every time. Once a user posts a content, the framework would forward the content to the "feed" collection owned by each of the followers. The front end just have to read or listen to a collection. This would also resolve the "Improve Caching of Profiles, Images, Etc." item on the todo list, and make the feed more reactive. 

No effort is required to modify the front end code, but it would be better to make the "feed" page listen to the firestore collection, so that new posts are automatically refreshed. The new framework can also run with current cloud function back end with no modifications in front end. 

Please let me know what you think. Thanks!

**Comment by mdanics** [comment]
Hey! 

This sounds really cool. I'd love to see it in action. I'm not sure if I would completely convert Fluttergram to use it (as it would result in another dependency) but if it works well, I would be interested in exploring making a demo branch or repo that showcases this integration

**Comment by mdanics** [comment]
I'm going to close this issue for now, but feel free to open a PR if you end up going about this!
