### ISSUE TITLE
Issue in README instruction.

### ISSUE THREAD

**Issue by reihanian** [mdanics/fluttergram#74]
Once your Firebase instance is created, you'll need to enable **anonymous** authentication.
Go to the Firebase Console for your new instance.
Click "Authentication" in the left-hand menu
Click the "sign-in method" tab
Click "Google" and enable it

-- I think you need to change the word of anonymous with **Google**

**Comment by mdanics** [comment]
Awesome, thanks for recognizing this and making a PR!
