### ISSUE TITLE
Why used google cloud functions?

### ISSUE THREAD

**Issue by mzmmoazam** [mdanics/fluttergram#80]

**Comment by mzmmoazam** [comment]
I just want to know if the reason is performance or otherwise. I think it kind of becomes vulnerable to various attacks given the hacker finds link like"https://us-central1-mp-rps.cloudfunctions.net/getFeed?uid=".

Please provide information or correct me ?

**Comment by mdanics** [comment]
The initial reason was to showcase an example of using cloud functions in conjunction with firebase, as well as giving the option of altering what the feed displays without pushing an app update.

For sure with the current implementation there is a security risk as all you need is someone's uid to view their feed, but it would be fairly trivial to implement authentication in the function (see [these docs](https://cloud.google.com/functions/docs/securing/authenticating)). 

If you end up implementing it, please submit a PR :)

Thanks!
