### ISSUE TITLE
CPU not supported (not compatible)

### ISSUE THREAD

**Issue by fzyzcjy** [mdanics/fluttergram#82]
When installing, my phone rejects and says that the CPU is not compatible... Maybe the app-release.apk should contain all the ABIs. Thanks!

**Comment by mdanics** [comment]
What device are you using?

**Comment by fzyzcjy** [comment]
The CPU is *Snapdragon 435*, and phone name is "huawei changxiang 7 plus".

**Comment by mdanics** [comment]
As I don't want to increase the size of the APK, I will keep it as it is. Feel free to fork the repo and build the APK for the devices you need.

Sorry!

**Comment by fzyzcjy** [comment]
OK
