### ISSUE TITLE
Error getting a feed: Http status 500 | userId xxxxxxxxxxxxxx

### ISSUE THREAD

**Issue by jaishirb** [mdanics/fluttergram#84]
Hi, everything seems to work fine, but as soon as I get logged in and try to load my posts, that's the error that flutter shows in the console, but it is necessary to say that the function to create the posts works fine, the error is when trying to load them.

**Comment by mdanics** [comment]
Did you do the steps outlined in this comment?
https://github.com/mdanics/fluttergram/issues/35#issuecomment-478391081

**Comment by joinity** [comment]
will you do the open points mentioned anytime soon? 
:)
