### ISSUE TITLE
Add CI/CD support

### ISSUE THREAD

**Issue by NikSWE** [mdanics/fluttergram#86]
> I update Fluttergram with new features and bugs fixes, but the apk may be behind master. Take a look at the changelog to see the most recent additions to the apk.

I would like to add `Circle CI` support for this app so that it becomes easy to release new `release.apk` and it stays in sync with master branch

**Comment by mdanics** [comment]
That would be great! Let me know if you need anything from me, otherwise, feel free to open a PR!

**Comment by NikSWE** [comment]
_First of all, loved the app_. 
![Screenshot from 2020-03-19 23-54-12](https://user-images.githubusercontent.com/34477129/77101262-0bb23880-6a3d-11ea-9dd6-d374a6475ac0.png)

As you can see in the screenshot that the **master branch** size is around 70 MB which is huge and would take some time on CI to build.

So to fix this you will have to remove the _release.apk blob_ from all git commit and force push to master branch. (this will bring the repo size to approx 5.4 MB)

[git forget-blob utility](https://ownyourbits.com/2017/01/18/completely-remove-a-file-from-a-git-repository-with-git-forget-blob/)

[would also recommend removing .iml files]

**Comment by mdanics** [comment]
Thanks! 

After some research, I think it will be better not to delete the apk and rewrite git history as there are many forks of the repo and it can cause some problems. 

I don't mind CI taking some time as there are not frequent updates to the repo. Let me know what's needed for the next steps!

**Comment by NikSWE** [comment]
okay, sure let me look into it
