### ISSUE TITLE
comments error

### ISSUE THREAD

**Issue by ajatsoft** [mdanics/fluttergram#87]
coments page not load coments from firestore, get circular progress widget

**Comment by mounagongi** [comment]
@ajatsoft please did you solve this problem?? I can't also solve the issue in the feed page.. did you have any solution?

**Comment by ajatsoft** [comment]
no, i cant use it

**Comment by mdanics** [comment]
Are there any errors in the console?

**Comment by mdanics** [comment]
Fixed - see #97 for an explanation
