### ISSUE TITLE
Video in news feed

### ISSUE THREAD

**Issue by venky9885** [mdanics/fluttergram#94]
In news feed only image is supported
Please support it for Video also in news feed
Can you please help me

**Comment by mdanics** [comment]
Hi, 

Fluttergram does not support video for the time being. I don't think it would be too difficult to implement. The ImagePicker plugin used can pick videos with `ImagePicker.pickVideo(...)`, and then you could use the following package to display videos https://pub.dev/packages/video_player. 

If you do end up implementing this, please submit a PR - it would be appreciated :)

Good luck!

**Comment by elgansayer** [comment]
I've done this using video player and adding a post type video/image.

Unfortunately, the app only took ideas from this repo and the code is too vastly different to PR anything. However, I would gladly help or add it when I have spare time.

**Comment by mdanics** [comment]
Sounds good! Thank you :)
