### ISSUE TITLE
HTTP Status 500 | UserId xxxxxxxxx

### ISSUE THREAD

**Issue by akiiii29** [mdanics/fluttergram#95]
follow your step but still got this : Error getting a feed: Http Status 500 | userId xxxxxxxx
code here
![image](https://user-images.githubusercontent.com/66854376/85260508-feba4080-b494-11ea-927a-2082beb6ea2b.png)

**Comment by akiiii29** [comment]
Problem solved, i dont have neccessary index. Solved by firebase functions:log

**Comment by islamawad94** [comment]
thank you brother , you are handsome guy

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by aliazimoshan** [comment]
@akiiii29 
hi,
I've got the same error, what did you change in the firebase function for solving this?

**Comment by akiiii29** [comment]
u just need to create an index in firebase
